### ISSUE TITLE
Adjust (very wide) right margin 

### ISSUE THREAD

**Issue by adagj** [NorESMhub/noresm-exp#10]
Hi @annefou ,
I wonder if it is possible to adjust the page width?
https://noresmhub.github.io/noresm-exp/noresm2_lm_spin/noresm2_lm_spin_intro.html
Now, half on the page is blank and that space would be very useful for adding more columns into tables. Is is possible to adjust it? I have googled a lot, but couldn't find any suggestions.

Best,
Ada

**Comment by annefou** [comment]
Yes. we can update the style and customize it. Before I would like to check if the new version of jupyter book is now stable enough to be installed so we could migrate the repo to the latest version (and then start to customize).

**Comment by adagj** [comment]
Sounds good. The documentation will be released on the 15th of June, so if we update before that would be great!

**Comment by annefou** [comment]
The "new" version is still not stable so better to update the style right now. We will migrate later.

**Comment by adagj** [comment]
Good, can you guide me to how and where I make such changes?

**Comment by annefou** [comment]
you can define your own styles in assets/custom/

**Comment by adagj** [comment]
Hi @annefou ,
I changed the style in assets/custom and the build failed. Then I changed it back to what it was before and the build still fails. I feel like an elephant surrounded by eggs...
The error I get is:

#!/bin/bash -eo pipefail
export PATH=$PATH:/home/circleci/.local/bin
ghp-import -p -n -f _site
Warning: Permanently added the RSA host key for IP address '140.82.112.4' to the list of known hosts.
ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Traceback (most recent call last):
  File "/home/circleci/.local/bin/ghp-import", line 8, in <module>
    sys.exit(main())
  File "/home/circleci/.local/lib/python2.7/site-packages/ghp_import.py", line 242, in main
    git.check_call('push', opts.remote, opts.branch, '--force')
  File "/home/circleci/.local/lib/python2.7/site-packages/ghp_import.py", line 106, in check_call
    sp.check_call(['git'] + list(args), **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'gh-pages', '--force']' returned non-zero exit status 128

Exited with code exit status 1
CircleCI received exit code 1

**Comment by annefou** [comment]
@adagj you have changed the keys used to push the generated web pages so it does not work anymore. I am teaching right now and will be busy teaching until tomorrow afternoon. I probably won't have time to revert your changes before that.

**Comment by adagj** [comment]
Hi @annefou ,
I have no idea how I did that... I have made many many new files under content/noresm2_mm_spin and I hope fixing key issues doesn't imply removing those. If so let me know so I can make some copies first :) Thanks for looking into this. And if you know how I made these changes, it would be good to know so I can avoid doing it again.

**Comment by annefou** [comment]
@adagj I think it is fixed now (I removed your key). I think it was added when going on circleci. The key needs to allow write (not read only).
