### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by adagj** [NorESMhub/noresm-exp#14]
Hi @annefou,
The NorESM2 experiment documentation fails to build after I changed nothing more than 1 link in one of the files - which is strange so I guess I have changed some rights (executing rights maybe?) just by opening the file- 
The timing is not very good as I just presented the webpage on the NorESM2 user workshop 5 minutes ago and will present it again on Thursday. And there are several links I need to change since the path has changes. What to do??

Ada

**Comment by annefou** [comment]
I am looking at it

**Comment by annefou** [comment]
Should be fixed now. It was related to the recent upgrade to 6.0 of nbconvert. We need to explicitely take an older version.
