### ISSUE TITLE
Failed to change table of contents

### ISSUE THREAD

**Issue by adagj** [NorESMhub/noresm-exp#6]
Hi Anne!
@annefou 
I changed the logo. That worked! Yeah!
I tried to add some sections to toc.yml in _data, that failed.
I also tried to add two files which will describe noresm experiments to the content folder. That failed.
Are they suppose to be saved in that folder? Is it more organized to add subfolders? E.g. NorESM2-LM spin up, NorESM2-MM spin up ....

I appreciate some start up help. I tried to look at the Jupyter book tutorial but the syntax seems to be different.

Ada

**Comment by annefou** [comment]
Which doc do you use https://legacy.jupyterbook.org/intro?
