### ISSUE TITLE
How to add a "simple" figure to a md file?

### ISSUE THREAD

**Issue by adagj** [NorESMhub/noresm-exp#8]
Hi @annefou ,

I'm trying to include a figure (Figure_4.png) at the bottom of this page:
https://noresmhub.github.io/noresm-exp/noresm2_lm_spin.html#%60%60%60{figure}-../images/Figure_4.png

I have included what I believed was the correct syntax in this file:
https://github.com/NorESMhub/noresm-exp/blob/master/content/noresm2_lm_spin.md

I have tried all the different options I can think of, but it is not going very well...

Ada

**Comment by annefou** [comment]
I'll make a suggestion asap (I am in a meeting until 11:00).

**Comment by annefou** [comment]
Dirty fix would be to use HTML:

```
<figure>
  <img src="Figure_4.png" alt="NorESM2-LM spinup simulations" style="width:250px">
  <figcaption><b>NorESM2-LM spinup simulations</b><br>
Upper left: Global and annual sum of DMS (dimethylsulfide).
Globally and annually averaged Surface (2m) air temperature (middle left), Net radiation @TOA (bottom left), SST (upper right). Global and volume averaged ocean temperature (middle right). </figcaption>
</figure>
```

**Comment by adagj** [comment]
Yes!!!!!! That worked. Merci!
